version: "3"
services:

  # zookeeper
  zookeeper:
    platform: linux/amd64
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  # kafka
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
     - kafka-net
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 5


  # risingwave
  risingwave:
    image: risingwavelabs/risingwave:v1.10.0
    ports:
    - 5690:5690
    - 5691:5691
    - 4566:4566
    entrypoint:
    - /risingwave/bin/risingwave
    - playground
    networks:
     - kafka-net
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/4566' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=mydb
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 10s
      retries: 5
    command: [ "postgres", "-c", "wal_level=logical" ]
    restart: always
    container_name: postgres
    networks:
     - kafka-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"  
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - "./grafana_configs/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml"
      - "./grafana_configs/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml"
      - "./grafana_configs:/var/lib/grafana/dashboards"
    networks:
      - kafka-net

  postgres_prepare:
    image: postgres
    depends_on: 
      postgres:
        condition: service_healthy
    command:
      - /bin/sh
      - -c
      - "psql postgresql://myuser:123456@postgres:5432/mydb < postgres_prepare.sql"
    volumes:
    - "./postgres_prepare.sql:/postgres_prepare.sql"      
    container_name: postgres_prepare
    restart: on-failure
    networks:
    - kafka-net


  risingwave-init:
    image: postgres:13
    depends_on:
      risingwave:
        condition: service_healthy
      postgres_prepare:
        condition: service_completed_successfully
    command: |
      sh -c "
      sleep 10 &&
      psql -h risingwave -p 4566 -d dev -U root -f /init.sql
      "
    volumes:
      - "./init.sql:/init.sql"
    networks:
      - kafka-net

  # kafka producer
  kafka-producer:
    build:
      context: .
      dockerfile: data-producers/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      risingwave-init:
        condition: service_completed_successfully
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    restart: always
    networks:
     - kafka-net

networks:
  kafka-net:
    driver: bridge
    name: kafka-net