services:
  warp:
      image: public.ecr.aws/warpstream-labs/warpstream_agent:latest
      ports:
       - "9092:9092"
      expose:
       - "9092"
      networks:
      - kafka-net
      command:
        - demo
      environment:
        # this is a no-op as it will default on the custom advertised hostname defined above, but you can change this if you want to use a different hostname with Kafka
        - WARPSTREAM_DISCOVERY_KAFKA_HOSTNAME_OVERRIDE=warp
      healthcheck:
        test: ["CMD-SHELL", "nc -z warp 9092"]
        interval: 5s
        timeout: 5s
        retries: 5
    
  kafka-producer:
    build:
      context: .
      dockerfile: data-producers/Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: warp:9092
    depends_on:
      warp:
        condition: service_healthy
    command: >
      sh -c "echo 'Waiting for Warpstream to fully initialize...' &&  
            python run-producers.py"
    restart: always
    networks:
      - kafka-net

  # risingwave
  risingwave:
    image: risingwavelabs/risingwave:latest
    ports:
     - 5690:5690
     - 5691:5691
     - 4566:4566
    entrypoint:
     - /risingwave/bin/risingwave
     - playground
    networks:
     - kafka-net

  risingwave_setup:
    image: postgres:17
    environment:
      PGPASSWORD: ""
    command: |
      /bin/sh -c "
        echo 'Waiting before running source commands...' && sleep 25 &&
        psql -h risingwave -p 4566 -d dev -U root -f /source_commands.sql &&
        echo 'Running materialized view commands...' &&
        psql -h risingwave -p 4566 -d dev -U root -f /mv_commands.sql &&
        echo 'RisingWave setup complete!'
      "
    volumes:
      - "./source_commands.sql:/source_commands.sql"
      - "./mv_commands.sql:/mv_commands.sql"
    container_name: risingwave_setup
    restart: on-failure
    networks:
      - kafka-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"  
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - "./grafana_configs/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml"
      - "./grafana_configs/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml"
      - "./grafana_configs:/var/lib/grafana/dashboards"
    depends_on:
      risingwave_setup:
        condition: service_completed_successfully
    networks:
      - kafka-net

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=mydb
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=myuser --dbname=mydb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: [ "postgres", "-c", "wal_level=logical" ]
    restart: always
    container_name: postgres
    networks:
     - kafka-net

  postgres_prepare:
    image: postgres:17
    depends_on: 
      postgres:
        condition: service_healthy
    environment:
      - PGPASSWORD=123456
    command:
      - /bin/sh
      - -c
      - |
        psql -h postgres -U myuser -d mydb -f /postgres_prepare.sql
    volumes:
      - "./postgres_prepare.sql:/postgres_prepare.sql"      
    container_name: postgres_prepare
    restart: on-failure
    networks:
      - kafka-net

  # topic producer
  
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
networks:
  kafka-net:
    driver: bridge
    name: kafka-net
