version: "3"
services:
  # # zookeeper
  # zookeeper:
  #   platform: linux/amd64
  #   image: wurstmeister/zookeeper
  #   container_name: zookeeper
  #   ports:
  #     - "2181:2181"
  #   networks:
  #     - kafka-net

  # # kafka
  # kafka:
  #   image: confluentinc/cp-kafka:7.5.3
  #   container_name: kafka
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9092:9092"
  #     - "29092:29092"
  #   expose:
  #     - "9092"
  #     - "29092"
  #   environment:
  #     KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092, LISTENER_DOCKER_EXTERNAL://localhost:29092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT, LISTENER_DOCKER_EXTERNAL:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  #   networks:
  #     - kafka-net


  warp:
      image: public.ecr.aws/warpstream-labs/warpstream_agent:latest
      ports:
       - "9092:9092"
      expose:
       - "9092"
      networks:
      - kafka-net
      command:
        - demo
      environment:
        # this is a no-op as it will default on the custom advertised hostname defined above, but you can change this if you want to use a different hostname with Kafka
        - WARPSTREAM_DISCOVERY_KAFKA_HOSTNAME_OVERRIDE=warp
      healthcheck:
        # Wait for the Agent to finish setting up the demo before marking it as healthy
        # to delay the diagnose-connection command from running for a few seconds.
        test: ["CMD", "kcmd", "-bootstrap-host", "warp", "-type", "diagnose-connection"]
        interval: 5s
        timeout: 15s
        retries: 5

 # risingwave
  risingwave:
    image: risingwavelabs/risingwave:latest
    ports:
      - 5690:5690
      - 5691:5691
      - 4566:4566
    entrypoint:
      - /risingwave/bin/risingwave
      - playground
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5690/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - kafka-net

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=mydb
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=myuser --dbname=mydb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: [ "postgres", "-c", "wal_level=logical" ]
    restart: always
    container_name: postgres
    networks:
      - kafka-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - "./grafana_configs/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml"
      - "./grafana_configs/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml"
      - "./grafana_configs:/var/lib/grafana/dashboards"
    networks:
      - kafka-net
  risingwave-init:
    image: postgres:17
    depends_on:
      risingwave:
        condition: service_healthy
      postgres_prepare:
        condition: service_completed_successfully

    command: |
      sh -c "
      sleep 10 &&
      until pg_isready -h risingwave -p 4566 -U root; do
        echo 'Waiting for RisingWave to be ready...'
        sleep 5
      done &&
      echo 'RisingWave is ready, running init script...' &&
      psql -h risingwave -p 4566 -d dev -U root -v ON_ERROR_STOP=1 -f /init.sql &&
      echo 'Init script completed successfully'
      "
    volumes:
      - "./init.sql:/init.sql"
    networks:
      - kafka-net
    restart: on-failure

  postgres_prepare:
    image: postgres:17
    depends_on:
      - postgres
    command:
      - /bin/sh
      - -c
      - "psql postgresql://myuser:123456@host.docker.internal:5433/mydb < postgres_prepare.sql"
    volumes:
      - "./postgres_prepare.sql:/postgres_prepare.sql"
    container_name: postgres_prepare
    restart: on-failure

  # kafka producer
  kafka-producer:
    build:
      context: .
      dockerfile: data-producers/Dockerfile
    depends_on:
      - warp
    environment:
      KAFKA_BOOTSTRAP_SERVERS: warp:9092
    restart: always
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
    name: kafka-net
